#!/bin/zsh

# Pywal
(cat ~/.cache/wal/sequences &)
source ~/.cache/wal/colors-tty.sh

# Dircolors
if command -v dircolors > /dev/null; then
    if [ -r $XDG_CONFIG_HOME/sh/dircolors ]; then
	eval $(dircolors -b $XDG_CONFIG_HOME/sh/dircolors)
    fi
fi

# Termcolors
if [ -f $XDG_CONFIG_HOME/sh/termcolors ]; then
    . $XDG_CONFIG_HOME/sh/termcolors
fi
