#!/bin/bash
#     _              _     _____            ___ ______
#    / \   _ __   __| |_ _|___ /  __ _ ___ / _ \  ___/
#   / _ \ | '_ \ / _` | '__||_ \ / _` / __/ | | \ \
#  / ___ \| | | | (_| | |  ___) | (_| \__ \ |_| |\ \
# /_/   \_|_| |_|\__,_|_| |____/ \__,_|___/\___/  \_\
# https://github.com/Andr3as07
#
# Displays the shell prompt for bash

# NOTE: Currently no support for bold text
# NOTE: Currently no support for displaying error codes
export TERMINAL="bash"

color_white="\[\033[37m\]"
color_red="\[\033[31m\]"
color_cyan="\[\033[36m\]"
color_yellow="\[\033[33m\]"
color_green="\[\033[32m\]"
color_blue="\[\033[34m\]"

esc_name="\u"
esc_host="\h"

source ~/.config/sh/promptsettings

function prompt_cmd() {
    # Open Brace
    prompt=$color_default$default_prefix

    # User
    source ~/.config/sh/promptuser

    # Only show hostname on ssh
    source ~/.config/sh/prompthost

    prompt=$prompt":"

    # PWD
    source ~/.config/sh/promptpwd

    # Close Brace
	  prompt=$prompt$color_default$default_suffix

    # Git
    source ~/.config/sh/promptgit

    # Development environment
    source ~/.config/sh/promptpy
    source ~/.config/sh/promptjava
    source ~/.config/sh/promptphp

    # Count running jobs
    source ~/.config/sh/promptjobs

    # Export
    export PS1="$prompt$color_default $prompt_tip "
    export PS2="$prompt_tip "
}

PROMPT_COMMAND=prompt_cmd
