#!/bin/bash
# NOTE: Currently no support for bold text
# NOTE: Currently no support for displaying error codes

export TERMINAL="bash"

color_white="\[\033[37m\]"
color_red="\[\033[31m\]"
color_cyan="\[\033[36m\]"
color_yellow="\[\033[33m\]"
color_green="\[\033[32m\]"
color_blue="\[\033[34m\]"

esc_name="\u"
esc_host="\h"

source ~/.config/sh/promptsettings

function prompt_cmd() {
    p=`pwd`

    # Readonly
    ro=0
    if [ ! -w "$p" ]; then
	ro=1
    fi

    if [ $ro = 0 ]; then
	prompt="$color_default["
    else
	prompt=$color_ro"["$color_default
    fi

    # User
    source ~/.config/sh/promptuser

    # Only show hostname on ssh
    source ~/.config/sh/prompthost

    prompt=$prompt":"

    # PWD
    source ~/.config/sh/promptpwd

    # Readonly
    if [ $ro = 0 ]; then
	prompt=$prompt$color_default"]"
    else
	prompt=$prompt$color_ro"]"$color_default
    fi

    # Git
    source ~/.config/sh/promptgit

    # Development environment
    source ~/.config/sh/promptpy
    source ~/.config/sh/promptjava

    # Count running jobs
    source ~/.config/sh/promptjobs

    # Export
    export PS1="$prompt$color_default $prompt_tip "
    export PS2="$prompt_tip "
}

PROMPT_COMMAND=prompt_cmd
