return {
    'nguyenvukhang/nvim-toggler',
    event = { "BufReadPre", "BufNewFile" },
    opts = {
        inverses = {
            ['vim'] = 'emacs',
            ['true'] = 'false',
            ['True'] = 'False',
            ['yes'] = 'no',
            ['on'] = 'off',
            ['left'] = 'right',
            ['up'] = 'down',
            ['enable'] = 'disable',
            ['!='] = '==',
            ['!=='] = '===',
            ['1'] = '0',
            ['in'] = 'out',
            ['break'] = 'continue',
            ['get'] = 'set',
            ['struct'] = 'class',
            ['enum'] = 'union',
            ['||'] = '&&',
            ['|'] = '&',
            ['++'] = '--',
            ['->'] = '.',
            ['and'] = 'or',
            ['min'] = 'max',
            ['push'] = 'pop',
            ['open'] = 'close',
            ['start'] = 'stop',
            ['first'] = 'last',
            ['before'] = 'after',
            ['show'] = 'hide',
            ['add'] = 'remove',
            ['read'] = 'write',
            ['import'] = 'export',
            ['encode'] = 'decode',
            ['encrypt'] = 'decrypt',
            ['input'] = 'output',
            ['request'] = 'response',
            ['public'] = 'private',
            ['sync'] = 'async',
            ['local'] = 'global',
            ['row'] = 'column',
            ['width'] = 'height',
        },
        remove_default_keybinds = false, -- default: <leader>i
        remove_default_inverses = true,
        autoselect_longest_match = true
    },
    config = function (_, opts)
        require('nvim-toggler').setup(opts)
    end
}
