[general]
import = [ "~/.cache/wal/colors-alacritty.toml" ]

[window]
padding = { x = 20, y = 20 }
dynamic_padding = true
decorations_theme_variant = "dark"

[scrolling]
history = 100000

[cursor]
style = { shape = "Block", blinking = "On" }

[font]
size = 14.0

[font.normal]
family = "ComicShannsMono Nerd Font"
style = "Regular"

[font.bold]
family = "ComicShannsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Monaspace Radon"
style = "Bold Italic"

[font.italic]
family = "Monaspace Radon"
style = "Italic"
